
#Install Node to build and run application
FROM node:16 as build

#set directory to app
WORKDIR /usr/src/app

#copy package.json to said folder
COPY package*.json ./

#run npm for production
RUN npm ci --only=production

#copy files
COPY . .

# RUN npm run build --prod
FROM nginx1.15.8-alpine

COPY --from=build /usr/src/app/dist /usr/share/nginx/html
# CMD ["node", "server.js"]


FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install --force --only=production --silent

COPY . ./

EXPOSE 4200

RUN ng serve

#CMD [ "node", "ng build" ]


